version: "3.8"
services:
    redis:
        image: "redis:alpine"
        restart: unless-stopped

    twitch-bot:
        build: "twitchBot/"
        env_file: twitch.env
        restart: unless-stopped
        depends_on:
            - redis

    discord-bot:
        build: "discordBot/"
        env_file: discord.env
        restart: unless-stopped
        depends_on:
            - redis

    rest-api:
        build: "RestAPI/"
        env_file: restapi.env
        restart: unless-stopped
        depends_on:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`api.website.com`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"

    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
            - "--api.dashboard=false"
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=security@website.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "443:443"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
